# Generated by Django 2.2.4 on 2022-02-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=100, verbose_name='代码 id')),
                ('code_content', models.TextField(blank=True, null=True, verbose_name='代码内容')),
                ('code_result', models.TextField(blank=True, null=True, verbose_name='代码输出结果')),
                ('errors', models.TextField(blank=True, null=True)),
                ('compile_status', models.CharField(max_length=100)),
                ('run_status_time', models.IntegerField(default=0, null=True)),
                ('run_status_memory', models.IntegerField(default=0, null=True)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
