# Generated by Django 2.2.4 on 2022-04-14 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_id', models.CharField(max_length=100, unique=True, verbose_name='代码id')),
                ('code_result', models.TextField(blank=True, null=True, verbose_name='代码输出结果')),
                ('errors', models.TextField(blank=True, null=True)),
                ('compile_status', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApp.MyCourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True, verbose_name='代码内容')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_editor.Codes', to_field='code_id')),
            ],
        ),
    ]
