# Generated by Django 2.2.4 on 2022-03-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_editor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('topic_img', models.ImageField(upload_to='result_images/', verbose_name='result_image')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_editor.Codes')),
            ],
        ),
    ]
