# Generated by Django 2.2.4 on 2022-03-27 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_editor', '0002_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='code_content',
            field=models.TextField(blank=True, null=True, verbose_name='code_content'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='code_id',
            field=models.CharField(max_length=100, verbose_name='code_id'),
        ),
    ]
