# Generated by Django 2.2.4 on 2022-03-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_editor', '0003_auto_20220327_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='code_result',
            field=models.TextField(blank=True, null=True, verbose_name='code result'),
        ),
    ]
