# Generated by Django 2.2.4 on 2022-03-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_editor', '0004_auto_20220327_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codes',
            name='code_content',
            field=models.TextField(blank=True, null=True, verbose_name='代码内容'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='code_id',
            field=models.CharField(max_length=100, verbose_name='代码id'),
        ),
        migrations.AlterField(
            model_name='codes',
            name='code_result',
            field=models.TextField(blank=True, null=True, verbose_name='代码输出结果'),
        ),
    ]
