# Generated by Django 2.2.4 on 2022-03-27 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('online_editor', '0005_auto_20220327_1840'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Images',
        ),
    ]
