# Generated by Django 2.2.4 on 2022-03-28 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_editor', '0006_delete_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codes',
            name='code_content',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='run_status_memory',
        ),
        migrations.RemoveField(
            model_name='codes',
            name='run_status_time',
        ),
        migrations.AlterField(
            model_name='codes',
            name='code_id',
            field=models.CharField(max_length=100, unique=True, verbose_name='代码id'),
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField(blank=True, null=True, verbose_name='代码内容')),
                ('code_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_editor.Codes', to_field='code_id')),
            ],
        ),
    ]
