# Generated by Django 2.2.4 on 2022-04-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_editor', '0008_auto_20220328_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='代码内容'),
        ),
    ]
