# Generated by Django 2.2.4 on 2021-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='tags',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
