# Generated by Django 2.2.4 on 2021-10-21 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='img_height',
            field=models.IntegerField(blank=True, null=True, verbose_name='img height'),
        ),
        migrations.AddField(
            model_name='topic',
            name='img_width',
            field=models.IntegerField(blank=True, null=True, verbose_name='img width'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='related_courses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courseApp.MyCourse'),
        ),
    ]
