# Generated by Django 2.2.4 on 2022-04-14 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courseApp', '0001_initial'),
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='identity.Admin'),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='related_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseApp.Topic'),
        ),
    ]
