# Generated by Django 2.2.4 on 2021-07-31 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='subtopic_id',
            field=models.CharField(max_length=20, null=True, verbose_name='详细课程id'),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='topic_id',
            field=models.CharField(choices=[('1', 'Python3 教程'), ('2', 'Python3 高阶教程'), ('3', 'Python3 待定')], max_length=20, null=True, verbose_name='课程类型id'),
        ),
    ]
