# Generated by Django 2.2.4 on 2022-02-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.TextField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_img',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to='topic_imgs', verbose_name='topic_image', width_field='img_width'),
        ),
    ]
