# Generated by Django 2.2.4 on 2022-02-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='teacher_id',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
