# Generated by Django 2.2.4 on 2022-04-25 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_auto_20220414_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
