# Generated by Django 2.2.4 on 2021-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_auto_20210801_0157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mycourse',
            name='subtopic_title',
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='topic_id',
            field=models.CharField(choices=[('2', 'Python3 高阶教程'), ('1', 'Python3 教程'), ('3', 'Python3 待定')], max_length=20, null=True, verbose_name='课程类型id'),
        ),
    ]
