# Generated by Django 2.2.4 on 2022-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_topic_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='update_date',
            field=models.DateTimeField(auto_now=True, max_length=20, verbose_name='更新时间'),
        ),
    ]
