# Generated by Django 2.2.4 on 2022-02-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0002_auto_20220221_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='subtopic_id',
            field=models.IntegerField(verbose_name='课程id'),
        ),
    ]
