# Generated by Django 2.2.4 on 2021-10-24 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_auto_20211023_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='subtopic_id',
            field=models.CharField(default=2, max_length=20, unique=True, verbose_name='子类型id'),
            preserve_default=False,
        ),
    ]
