# Generated by Django 2.2.4 on 2022-02-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0003_auto_20220227_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='id',
            field=models.AutoField(auto_created=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
