# Generated by Django 2.2.4 on 2022-03-06 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0004_auto_20220228_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_img',
            field=models.ImageField(blank=True, height_field='img_height', null=True, upload_to='topic_imgs/', verbose_name='topic_image', width_field='img_width'),
        ),
    ]
