# Generated by Django 2.2.4 on 2022-03-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0005_auto_20220306_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='img_height',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='img_width',
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_img',
            field=models.ImageField(blank=True, null=True, upload_to='topic_imgs/', verbose_name='topic_image'),
        ),
    ]
