# Generated by Django 2.2.4 on 2021-09-07 08:59

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0005_auto_20210804_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='description',
            field=DjangoUeditor.models.UEditorField(default='请输入课程内容', verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='mycourse',
            name='topic_id',
            field=models.CharField(choices=[('3', 'Python3 待定'), ('1', 'Python3 教程'), ('2', 'Python3 高阶教程')], max_length=20, null=True, verbose_name='课程类型id'),
        ),
    ]
