# Generated by Django 2.2.4 on 2021-09-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0006_auto_20210907_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycourse',
            name='topic_id',
            field=models.CharField(choices=[('3', 'Python3 待定'), ('2', 'Python3 高阶教程'), ('1', 'Python3 教程')], max_length=20, null=True, verbose_name='课程类型id'),
        ),
    ]
