# Generated by Django 2.2.4 on 2022-03-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0006_auto_20220306_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('img_name', models.CharField(max_length=50)),
                ('img', models.ImageField(blank=True, null=True, upload_to='topic_imgs/', verbose_name='topic_image')),
            ],
        ),
    ]
