# Generated by Django 2.2.4 on 2022-03-07 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0008_auto_20220306_2309'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
