# Generated by Django 2.2.4 on 2022-04-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseApp', '0009_delete_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycourse',
            name='hint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mycourse',
            name='test_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
